### DISCUSSION TITLE
Camera usage

### DISCUSSION THREAD

**Discussion by sunjaxx** [timmo001/system-bridge#2870] [Q&A]
Hi, I just installed this. I mainly wanted to be able to have a sensor in HA reflecting whether a (USB) webcam is in use.

Is "camera_usage" supposed to help with that? I tried with two different webcams but get:

"camera_usage":[0 items
]

(And by the way, how would I "expose" that count / sensor to HA?) Thanks!

**Comment by sunjaxx** [comment]
anyone....? :-)

**Comment by sunjaxx** [comment]
I think I managed with this, in case it helps others:

```
binary_sensor:
  - platform: rest
    resource: http://192.168.xxx.XXX:9170/api/data/system/camera_usage
    value_template: "{{ value_json.camera_usage |length > 0}}"
    name: webcam in use
    headers: 
      api-key: XXXXXXXXXXXXXXXXXXXXXXXXXXX
```
